routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {


    return view('welcome');


});

Route::post('deploy', 'DeployController@deploy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resources([
        'clients' => 'ClientController',
        'make' => 'MakeController',
        'type' => 'TypeController',
    ]);
});

resources/views/partials/control-sidebar.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->

<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

resources/views/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 0.0.1 beta
    </div>
    <strong>Copyright &copy; 2020 <a href="http://itxp.ro">itxp.ro</a>.</strong> Toate drepturile rezervate.
</footer>

resources/views/partials/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>AdminLBM | Dashboard</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
<!-- Ionicons -->
{{--<link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">--}}
{{--<!-- DataTables -->--}}
{{--<link rel="stylesheet" href="/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">--}}
<!-- Theme style -->
<link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">
{{--<!-- Morris chart -->--}}
{{--<link rel="stylesheet" href="/bower_components/morris.js/morris.css">--}}
{{--<!-- jvectormap -->--}}
{{--<link rel="stylesheet" href="/bower_components/jvectormap/jquery-jvectormap.css">--}}
{{--<!-- Date Picker -->--}}
{{--<link rel="stylesheet" href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">--}}
{{--<!-- Daterange picker -->--}}
{{--<link rel="stylesheet" href="/bower_components/bootstrap-daterangepicker/daterangepicker.css">--}}
{{--<!-- bootstrap wysihtml5 - text editor -->--}}
{{--<link rel="stylesheet" href="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">--}}

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

@stack('css')

resources/views/partials/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/dist/img/user2-160x160.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">Navigatie Principala</li>
            {{--<li class="active treeview">--}}
                {{--<a href="#">--}}
                    {{--<i class="fa fa-dashboard"></i> <span>Tablou de bord</span>--}}
                    {{--<span class="pull-right-container">--}}
                    {{--<i class="fa fa-angle-left pull-right"></i>--}}
                    {{--</span>--}}
                {{--</a>--}}
                {{--<ul class="treeview-menu">--}}
                {{--<li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>--}}
                {{--<li><a href="/index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>--}}
                {{--</ul>--}}
            {{--</li>--}}
{{--            <li class="treeview">--}}
{{--                <a href="#">--}}
{{--                    <i class="fa fa-download fa-fw" aria-hidden="true"></i> <span>Comenzi primite</span>--}}
{{--                    <span class="pull-right-container">--}}
{{--              <i class="fa fa-angle-left pull-right"></i>--}}
{{--            </span>--}}
{{--                </a>--}}
{{--                <ul class="treeview-menu">--}}
{{--                    <li><a href="{{ route('receivedOrders.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Adauga comanda primita</a></li>--}}
{{--                    <li><a href="{{ route('receivedOrders.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista comenzi primite</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}

{{--            <li class="treeview">--}}
{{--                <a href="#">--}}
{{--                    <i class="fa fa-upload fa-fw" aria-hidden="true"></i> <span>Comenzi emise</span>--}}
{{--                    <span class="pull-right-container">--}}
{{--              <i class="fa fa-angle-left pull-right"></i>--}}
{{--            </span>--}}
{{--                </a>--}}
{{--                <ul class="treeview-menu">--}}
{{--                    <li><a href="{{ route('issuedOrders.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista comenzi emise</a></li>--}}

{{--                </ul>--}}
{{--            </li>--}}

{{--            <li class="treeview">--}}
{{--                <a href="#">--}}
{{--                    <i class="fa fa-book fa-fw" aria-hidden="true"></i> <span>Deconturi</span>--}}
{{--                    <span class="pull-right-container">--}}
{{--              <i class="fa fa-angle-left pull-right"></i>--}}
{{--            </span>--}}
{{--                </a>--}}
{{--                <ul class="treeview-menu">--}}
{{--                    <li><a href="{{ route('trips.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Decont nou</a></li>--}}
{{--                    <li><a href="{{ route('trips.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista deconturi</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li class="treeview">--}}
{{--                <a href="#">--}}
{{--                    <i class="fa fa-car fa-fw" aria-hidden="true"></i> <span>Flota</span>--}}
{{--                    <span class="pull-right-container">--}}
{{--              <i class="fa fa-angle-left pull-right"></i>--}}
{{--            </span>--}}
{{--                </a>--}}
{{--                <ul class="treeview-menu">--}}
{{--                    <li><a href="{{ route('cars.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Adauga masina</a></li>--}}
{{--                    <li><a href="{{ route('cars.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista masini</a></li>--}}
{{--                    <li><a href="{{ route('cars.expenses') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista cheltuieli</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li class="treeview">--}}
{{--                <a href="#">--}}
{{--                    <i class="fa fa-money fa-fw" aria-hidden="true"></i> <span>Cheltuieli</span>--}}
{{--                    <span class="pull-right-container">--}}
{{--              <i class="fa fa-angle-left pull-right"></i>--}}
{{--            </span>--}}
{{--                </a>--}}
{{--                <ul class="treeview-menu">--}}
{{--                    <li><a href="{{ route('expenses.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Adauga cheltuiala</a></li>--}}
{{--                    <li><a href="{{ route('expenses.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista cheltuieli</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li class="treeview">--}}
{{--                <a href="#">--}}
{{--                    <i class="fa fa-male fa-fw" aria-hidden="true"></i>--}}
{{--                    <span>Soferi</span>--}}
{{--                    <span class="pull-right-container">--}}
{{--              <i class="fa fa-angle-left pull-right"></i>--}}
{{--            </span>--}}
{{--                </a>--}}
{{--                <ul class="treeview-menu">--}}
{{--                    <li><a href="{{ route('drivers.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Adauga sofer</a></li>--}}
{{--                    <li><a href="{{ route('drivers.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista soferi</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li class="treeview">--}}
{{--                <a href="#">--}}
{{--                    <i class="fa fa-file-text fa-fw" aria-hidden="true"></i> <span>Facturi</span>--}}
{{--                    <span class="pull-right-container">--}}
{{--              <i class="fa fa-angle-left pull-right"></i>--}}
{{--            </span>--}}
{{--                </a>--}}
{{--                <ul class="treeview-menu">--}}
{{--                    <li><a href="{{ route('invoices.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Factura noua</a></li>--}}
{{--                    <li><a href="{{ route('invoices.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista facturi</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-address-card fa-fw" aria-hidden="true"></i>
                    <span>Clienti</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('clients.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Adauga client</a></li>
                    <li><a href="{{ route('clients.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista clienti</a></li>
                </ul>
            </li>
{{--            <li class="treeview">--}}
{{--                <a href="#">--}}
{{--                    <i class="fa fa-truck fa-fw" aria-hidden="true"></i>--}}
{{--                    <span>Transportatori</span>--}}
{{--                    <span class="pull-right-container">--}}
{{--              <i class="fa fa-angle-left pull-right"></i>--}}
{{--            </span>--}}
{{--                </a>--}}
{{--                <ul class="treeview-menu">--}}
{{--                    <li><a href="{{ route('carriers.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Adauga transportator</a></li>--}}
{{--                    <li><a href="{{ route('carriers.index') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Lista transportatori</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-gear fa-fw" aria-hidden="true"></i> <span>Setari</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">

                    <li class="treeview">
                        <a href="#"><i class="fa fa-industry"></i> Producatori
                            <span class="pull-right-container">
                              <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{{ route('make.create') }}"><i class="fa fa-plus"></i> Adauga producator</a></li>
{{--                            <li><a href="{{ route('settings.make.index') }}"><i class="fa fa-list-alt"></i> Lista tari</a></li>--}}
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#"><i class="fa fa-car"></i> Modele
                            <span class="pull-right-container">
                              <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{{ route('type.create') }}"><i class="fa fa-plus"></i> Adauga model</a></li>
                            {{--                            <li><a href="{{ route('settings.make.index') }}"><i class="fa fa-list-alt"></i> Lista tari</a></li>--}}
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#"><i class="fa fa-user"></i> Useri
                            <span class="pull-right-container">
                              <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
{{--                            <li><a href="{{ route('settings.users.create') }}"><i class="fa fa-plus"></i> Adauga user</a></li>--}}
{{--                            <li><a href="{{ route('settings.users.index') }}"><i class="fa fa-list-alt"></i> Lista useri</a></li>--}}
                        </ul>
                    </li>


                </ul>
            </li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>