routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {


    return view('welcome');


});

Route::post('deploy', 'DeployController@deploy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resources([
        'clients' => 'ClientController',
        'make' => 'MakeController',
        'type' => 'TypeController',
    ]);
});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    //
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('clients.create');

        dd(1);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
//        dd('dads');
        return view('clients.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        //
    }
}

resources/views/clients/create.blade.php
@extends('layouts.main')

@section('head-inject')
  <!-- DataTables -->
  <link rel="stylesheet" href="/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Clienti
      <small>Client nou</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i>Acasa</a></li>
      <li><a href="#">Clienti</a></li>
      <li class="active">Client nou</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Client nou</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" method="POST" action="{{ route('clients.store') }}">

            {{ csrf_field() }}

            <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">

            <div class="box-body">
              @if ($errors->any())
                <div class="alert alert-danger">
                  <ul>
                    @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                  </ul>
                </div>
              @endif
              <div class="form-group">
                <label for="inputName">Nume*</label>
                <input type="text" class="form-control" id="inputName" placeholder="Exemplu SRL" value="{{ old('name') }}" name="name">
              </div>
              <div class="form-group">
                <label for="inputCIF">CIF</label>
                <input type="text" class="form-control" id="inputCIF" placeholder="DE-123456 / 123123 / RO456456" value="{{ old('cif') }}" name="cif">
              </div>
{{--              <div class="form-group">--}}
{{--                <label for="inputORC">Numar Registrul Comertului</label>--}}
{{--                <input type="text" class="form-control" id="inputORC" placeholder="J03/456/2008" value="{{ old('orc') }}" name="orc">--}}
{{--              </div>--}}
{{--              <div class="form-group">--}}
{{--                <label for="inputCountry">Tara</label>--}}
{{--                <select class="form-control" id="inputCountry" name="country_id">--}}
{{--                  @foreach($make as $country)--}}
{{--                    <option value="{{ $country->id }}"@if(old('country_id')==$country->id) selected @endif>{{ $country->name }}</option>--}}
{{--                  @endforeach--}}
{{--                </select>--}}
{{--              </div>--}}
{{--              <div class="form-group">--}}
{{--                <label for="inputAddress">Adresa</label>--}}
{{--                <input type="text" class="form-control" id="inputAddress" placeholder="Koln 65432, Strase XXX, no. 5" value="{{ old('address') }}" name="address">--}}
{{--              </div>--}}
{{--              <div class="form-group">--}}
{{--                <label for="inputBank">Banca</label>--}}
{{--                <input type="text" class="form-control" id="inputBank" placeholder="BRD" value="{{ old('bank') }}" name="bank">--}}
{{--              </div>--}}
{{--              <div class="form-group">--}}
{{--                <label for="inputIBAN">IBAN</label>--}}
{{--                <input type="text" class="form-control" id="inputIBAN" placeholder="ROXX YYYY ZZZZ ZZZZ ZZZZ ZZZZ" value="{{ old('iban') }}" name="iban">--}}
{{--              </div>--}}
{{--              <div class="form-group">--}}
{{--                <label for="inputSWIFT">SWIFT / BIC</label>--}}
{{--                <input type="text" class="form-control" id="inputSWIFT" placeholder="INGBROBU" value="{{ old('swift') }}" name="swift">--}}
{{--              </div>--}}
              <div class="form-group">
                <label for="inputPhone">Telefon</label>
                <input type="text" class="form-control" id="inputPhone" placeholder="0723 123 123" value="{{ old('phone') }}" name="phone">
              </div>
              <div class="form-group">
                <label for="inputEmail">Email</label>
                <input type="email" class="form-control" id="inputEmail" placeholder="Email" value="{{ old('email') }}" name="email">
              </div>
{{--              <div class="form-group">--}}
{{--                <label for="inputContact">Contact</label>--}}
{{--                <input type="text" class="form-control" id="inputContact" placeholder="Klaus George" value="{{ old('contact') }}" name="contact">--}}
{{--              </div>--}}
              <div class="form-group">
                <label for="inputDiscount">Adaos %</label>
                <input type="number" class="form-control" id="inputDiscount" placeholder="20" value="{{ old('markup') }}" name="markup">
              </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Salveaza</button>
            </div>
          </form>
        </div>
      </div>
        <!-- /.box -->

    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->

@endsection

@push('css')

  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">

@endpush

@push('scripts')

  <!-- bootstrap datepicker -->
  <script src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
  <script>
      //Date picker
      $('#expiryDate').datepicker({
          format: 'yyyy/mm/dd',
          autoclose: true
      })
      //Date picker
      $('#date').datepicker({
          format: 'yyyy/mm/dd',
          autoclose: true
      })
  </script>

@endpush

resources/views/clients/index.blade.php
@extends('layouts.main')

@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endpush

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Flota
      <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Dashboard</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Clienti</h3>

            <div>
                <a href="{{ route('clients.create') }}" class="btn btn-success">Adauga client</a>
            </div>

          </div>
          <!-- /.box-header -->
          <div class="box-body" style="white-space:nowrap;">


            <table class="table table-bordered" id="cars-table" width="100%">
              <thead>
              <tr>
                <th>Nume</th>
                <th>CUI</th>
                <th>Tara</th>
                <th>Telefon</th>
              </tr>
              </thead>
            </table>

          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->

@endsection

@push('scripts')

  <!-- DataTables -->
  <script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

  <!-- page script -->
  {{--<script>--}}
      {{--$(function () {--}}
          {{--// $('#example1').DataTable()--}}
          {{--$('#example1').DataTable({--}}
              {{--'paging'      : true,--}}
              {{--'lengthChange': false,--}}
              {{--// 'searching'   : false,--}}
              {{--// "columns": [--}}
              {{--//     { "searchable": false },--}}
              {{--//     null,--}}
              {{--//     null,--}}
              {{--//     null,--}}
              {{--//     null--}}
              {{--// ],--}}
              {{--'ordering'    : true,--}}
              {{--'info'        : true,--}}
              {{--'autoWidth'   : false,--}}
              {{--// 'filtering'   : true--}}
          {{--})--}}
      {{--})--}}
  {{--</script>--}}

  <script>
      $(function() {
          $('#cars-table').DataTable({
              // responsive: true,
              processing: true,
              serverSide: true,
              ajax: '{!! route('data.clients') !!}',
              columns: [
                  { data: 'name', name: 'name' },
                  { data: 'cif', name: 'cif' },
                  { data: 'country', name: 'make.name' },
                  { data: 'phone', name: 'phone' },
              ],
              "scrollX": true,
              "order": [[ 0, "asc" ]],
              // columnDefs: [
              //     { responsivePriority: 1, targets: 0 },
              //     { responsivePriority: 2, targets: -1 }
              // ]
          });
      });
  </script>

@endpush